250 update (#40)
* TF 2.5.0 refresh

* Fixed absl patch for x86

* Fix build failure due to cub

* Some trial changes

* Fixed cpu build on ppc

* Fix needed for gcc 7

* Fix added to get rid of gcc 5.4 on x86

* Fix for error "external/com_google_absl/absl/functional/function_ref.h:100:29: error: parameter packs not expanded with '...'" which is fixed in upstream master

* Code cleanup

* Fix TF feedstock tests

* Limit resources used by bazel build

* Installed git in the test setup section

* Some clean up

* Some more cleanup

* Added grpcio as a dependency

* Updated patch name

* Disable TensorRT for ppc

* TRT to be kept disabled for py38 for now until TRT is updated

* Remove patch which is not needed with gcc 7.3

* Use same gcc 7.3 on both x86 and ppc

* Disable TensorRT temporarily

* Added comment

* Enable TRT again

* Enable TRT again

* Enable TRT